### ISSUE TITLE
add feature to remove routes, stop listening or reset router (client side)

### ISSUE THREAD

**Issue by tomaszkubacki** [justinfagnani/route#67]
I would like to add some (admin) users right to visit some locations - problem exists  when someone do relogin to regular account. I can't stop already added routes, so I would like to be able to remove routes, stop listening or reset router (client side)

**Comment by bgourlie** [comment]
I've run into a similar scenario, although I think there is a better solution to the problem.  Instead of micro-managing routes at runtime, we need a generic way to determine if a route should be denied.  This could be used for things like rejecting a route if the user isn't logged in or, in your case, if the user doesn't have the necessary privileges.  See this bug: https://github.com/dart-lang/route/issues/60

**Comment by bgourlie** [comment]
Not technically closed via https://github.com/dart-lang/route/commit/f3d78c37194d2e0415f1c00b22549a7684f31d57, but it allows the user to solve their original problem, which is to deny routes to certain users.

**Comment by pavelgj** [comment]
Assuming use-case addressed. If not, please file a new issue here: https://github.com/angular/route.dart/issues/new
